[package]
name = "hyprsunset-overdrive"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
fs2 = "0.4.3"
log = "0.4.27"
signal-hook = "0.3.17"
simplelog = "0.12.2"
sunrise = "1.2.1"
